//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraniteMason.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbCabinetMasonEntities : DbContext
    {
        public DbCabinetMasonEntities()
            : base("name=DbCabinetMasonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblAbout> TblAbouts { get; set; }
        public virtual DbSet<TblCabinet> TblCabinets { get; set; }
        public virtual DbSet<TblCabinetsGallery> TblCabinetsGalleries { get; set; }
        public virtual DbSet<TblCategory> TblCategories { get; set; }
        public virtual DbSet<TblContact> TblContacts { get; set; }
        public virtual DbSet<TblGallery> TblGalleries { get; set; }
        public virtual DbSet<TblGalleryPhoto> TblGalleryPhotoes { get; set; }
        public virtual DbSet<TblHome> TblHomes { get; set; }
        public virtual DbSet<TblHomeGallery> TblHomeGalleries { get; set; }
        public virtual DbSet<TblAdmin> TblAdmins { get; set; }
    }
}
