//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraniteMason.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblContact
    {
        public int ID { get; set; }
        public string Telefon { get; set; }
        public string Email { get; set; }
        public string Isim { get; set; }
        public string Aciklama { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    }
}
