//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraniteMason.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCabinetsGallery
    {
        public int ID { get; set; }
        public string GaleriResim { get; set; }
        public string GaleriBaslik { get; set; }
        public string GaleriFiyat { get; set; }
    }
}
