//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraniteMason.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCabinet
    {
        public int ID { get; set; }
        public string SliderResim { get; set; }
        public string SliderBaslik { get; set; }
        public string SliderAltBaslik { get; set; }
        public string SliderResim2 { get; set; }
        public string SliderBaslik2 { get; set; }
        public string SliderAltBaslik2 { get; set; }
    }
}
