//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraniteMason.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblHome
    {
        public int ID { get; set; }
        public string SliderBaslik { get; set; }
        public string SliderAltBaslik { get; set; }
        public string SliderResim { get; set; }
        public string HakkindaTarih1 { get; set; }
        public string HakkindaBaslik1 { get; set; }
        public string HakkindaAciklama1 { get; set; }
        public string HakkindaResim1 { get; set; }
        public string HakkindaTarih2 { get; set; }
        public string HakkindaAciklama2 { get; set; }
        public string HakkindaResim2 { get; set; }
        public string HakkindaBaslik2 { get; set; }
        public string HakkindaBaslik3 { get; set; }
        public string HakkindaTarih3 { get; set; }
        public string HakkindaAciklama3 { get; set; }
        public string HakkindaResim3 { get; set; }
        public string HakkindaBaslik4 { get; set; }
        public string HakkindaTarih4 { get; set; }
        public string HakkindaAciklama4 { get; set; }
        public string HakkindaResim4 { get; set; }
    }
}
